version: 2
updates:
  # Dependabot will handle Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/src_rust" # Root directory where Cargo.toml is located
    schedule:
      interval: "daily" # Check for updates daily
  - package-ecosystem: "helm"
    directory: "/infrastructure/gsp-platform" # Root of the repository
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/infrastructure/gsp-platform" # Root of the repository
    schedule:
      interval: "daily"
